server:  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          uri: https://github.com/tiagom18/microservice-loja-compasso/
          search-paths: fornecedor